/* ── Courses ───────────────────────────────────────────── */
export const courses = [
  {
    slug: "robotics-training",
    icon: "🤖",
    title: "Robotics Training",
    short: "Build real robots from scratch — mechanics, electronics & Arduino coding.",
    image: "/images/robotics-lab.webp",
    category: "Course",
    desc: "Learn mechanics, electronics & coding by building real robots from scratch.",
    tag: "Popular",
    price: "₹1,600",
    duration: "3 Months",
    level: "Beginner to Intermediate",
    audience: ["Students (10–18 years)", "Beginners with no coding experience", "Parents looking for STEM enrichment"],
    overview: "Learn mechanics, electronics, and coding by building real robots from scratch. This hands-on program covers everything from basic circuits and sensor integration to Arduino programming and autonomous navigation. Perfect for students aged 10–18 and beginners.",
    curriculum: [
      "Introduction to Robotics & Electronics",
      "Arduino Fundamentals & C++ Programming",
      "Sensor Integration (Ultrasonic, IR, LDR)",
      "Motor Control & Motion Systems",
      "Line Following Robot Build",
      "Obstacle Avoidance Robot Build",
      "Bluetooth-Controlled Robot",
      "Capstone Project Presentation",
    ],
    outcomes: [
      "Build 5+ working robots",
      "Understand electronics & circuits",
      "Learn Arduino C++ programming",
      "Certificate of Completion",
      "Competition-ready portfolio",
    ],
  },
  {
    slug: "arduino-embedded",
    icon: "⚡",
    title: "Arduino & Embedded Systems",
    short: "Master microcontrollers, sensors & C++ through 30+ hands-on projects.",
    image: "/images/arduino-kit.webp",
    category: "Course",
    desc: "Master microcontrollers, sensors & C++ for embedded innovation.",
    price: "₹1,600",
    duration: "2 Months",
    level: "Beginner to Advanced",
    audience: ["Engineering students", "Electronics hobbyists", "IoT enthusiasts"],
    overview: "Deep-dive into the world of embedded systems. Learn Arduino, sensors, actuators, IoT connectivity, and real-time systems through 30+ hands-on projects. This course bridges the gap between hobby electronics and professional embedded design.",
    curriculum: [
      "Arduino Architecture & IDE Setup",
      "Digital & Analog I/O",
      "Sensor Integration (Temperature, Humidity, Motion, Distance)",
      "Serial Communication & Display Interfaces",
      "Motor & Servo Control",
      "IoT — WiFi & Cloud Integration",
      "Advanced Projects (Smart Home, Weather Station, Security System)",
      "Capstone & Presentation",
    ],
    outcomes: [
      "30+ completed projects",
      "Arduino kit to keep",
      "IoT & cloud basics",
      "Certificate",
      "Ready for intermediate embedded roles",
    ],
  },
  {
    slug: "drone-workshop",
    icon: "🛸",
    title: "Drone Workshop",
    short: "Build and fly your own quadcopter — from frame assembly to first flight.",
    image: "/images/drone-workshop.webp",
    category: "Course",
    desc: "Build, fly and program your own quadcopter drone.",
    price: "₹1,600",
    duration: "2-Day Intensive / 4-Week Extended",
    level: "All Levels",
    audience: ["Students & hobbyists", "Aspiring drone pilots", "Engineering students"],
    overview: "Experience the thrill of building a drone from scratch. Learn about aerodynamics, motor selection, flight controller programming, and DGCA compliance. Fly the drone you build.",
    curriculum: [
      "Drone Anatomy & Aerodynamics",
      "Frame Assembly & Motor Configuration",
      "Flight Controller Setup",
      "Programming and GPS Integration",
      "First Flight & Calibration",
      "DGCA Guidelines & Safety",
    ],
    outcomes: [
      "Build a fully functional drone",
      "Understand flight dynamics",
      "DGCA awareness",
      "Certificate of Completion",
    ],
  },
  {
    slug: "stem-for-schools",
    icon: "🏫",
    title: "STEM Programs for Schools",
    short: "Turnkey robotics labs, curriculum & teacher training for grades 5–12.",
    image: "/images/stem-school.webp",
    category: "Schools",
    desc: "Curriculum-aligned robotics programs for grades 5–12.",
    tag: "Schools",
    price: "Custom",
    duration: "Customizable (Semester / Annual)",
    level: "Grades 5–12",
    audience: ["School principals & administrators", "CBSE/ICSE/State board schools", "Education trusts"],
    overview: "Curriculum-aligned STEM and robotics programs designed for schools and institutions. Includes lab setup, teacher training, student workshops, and competition coaching. We partner with schools to make hands-on STEM education accessible across all grade levels.",
    curriculum: [
      "Complete Robotics Lab Setup with Kits & Tools",
      "Grade-wise Lesson Plans (CBSE/ICSE Aligned)",
      "Teacher Training & Certification",
      "On-campus 1 to 5-day Robotics Workshops",
      "Competition Coaching for National Events",
      "Annual STEM Program Management",
    ],
    outcomes: [
      "Fully equipped robotics lab",
      "Trained faculty",
      "Student participation in competitions",
      "STEM culture in your school",
    ],
  },
  {
    slug: "robotics-competitions",
    icon: "🏆",
    title: "Robotics Competitions",
    short: "Train, build, and compete at national & international robotics events.",
    image: "/images/competition.webp",
    category: "Course",
    desc: "Dedicated coaching for WRO, RoboLeague, AICRA & national robotics events.",
    tag: "New",
    price: "₹2,500",
    duration: "6 Weeks Intensive",
    level: "Intermediate to Advanced",
    audience: ["Students who completed Robotics Training", "Competitive students aged 12–18", "School teams preparing for WRO / RoboLeague"],
    overview: "Take your robotics skills to the competition floor. Our dedicated competition coaching program prepares students for national and international events — WRO, RoboLeague, AICRA, Smart India Hackathon, and more. Expert mentors guide you through strategy, robot design, programming, and presentation.",
    curriculum: [
      "Competition Rules & Strategy (WRO / RoboLeague / AICRA)",
      "High-Performance Robot Design",
      "Speed & Precision Programming",
      "Sensor Fusion & Autonomous Navigation",
      "Sumo Bot & Line Follower Optimization",
      "Mock Competition Rounds & Feedback",
      "Team Coordination & Presentation Skills",
      "Final Competition Preparation",
    ],
    outcomes: [
      "Competition-ready robot",
      "Experience in 2+ mock competitions",
      "WRO / RoboLeague strategy knowledge",
      "Team leadership skills",
      "Certificate of Competition Training",
    ],
  },
  {
    slug: "online-learning",
    icon: "💻",
    title: "Online Learning & Support",
    short: "Live sessions, recorded content & lifetime mentorship — learn from anywhere.",
    image: "/images/online-learning.webp",
    category: "Course",
    desc: "Flexible online robotics & embedded systems learning with live mentorship.",
    tag: "Online",
    price: "₹999",
    duration: "Self-Paced + Live Sessions",
    level: "All Levels",
    audience: ["Students outside Hyderabad", "Working professionals", "Anyone who prefers flexible learning"],
    overview: "Can't make it to our Hyderabad lab? No problem. Our online program gives you access to recorded course content, weekly live mentoring sessions, project review calls, and a lifetime student community. Learn robotics and embedded systems from anywhere in India.",
    curriculum: [
      "Recorded Video Lessons (Arduino, Robotics, IoT)",
      "Live Weekly Q&A Sessions with Mentors",
      "Online Project Kits (delivered to your door)",
      "One-on-One Project Review Calls",
      "Peer Learning Community (Discord)",
      "Certification on Project Completion",
    ],
    outcomes: [
      "Lifetime access to recorded content",
      "3 live mentoring sessions included",
      "Project kit shipped to your address",
      "Online Certificate of Completion",
      "Access to Mech-E-Tron alumni community",
    ],
  },
];

/* ── Services ──────────────────────────────────────────── */
export const services = [
  {
    slug: "3d-printing",
    icon: "🖨️",
    title: "3D Printing",
    short: "High-precision FDM & resin printing for prototypes and project parts.",
    image: "/images/3d-printing.webp",
    category: "Service",
    desc: "Rapid prototyping with industrial-grade FDM & resin printers.",
    overview: "Bring your imagination to life with high-precision 3D printing. Perfect for prototypes, mechanical parts, and educational projects. We offer both FDM and resin printing with a wide range of materials.",
    capabilities: ["PLA, ABS, PETG, TPU materials", "Resin printing for fine detail", "Max build volume: 300×300×400mm", "Layer resolution down to 0.05mm", "Post-processing & finishing"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "laser-cutting",
    icon: "✂️",
    title: "Laser Cutting",
    short: "CO₂ & CNC precision cutting for acrylic, wood, MDF and more.",
    image: "/images/laser-cutting.webp",
    category: "Service",
    desc: "Precision cutting & engraving for acrylic, wood and more.",
    overview: "Achieve clean, precise, and intricate designs with advanced CNC and CO₂ laser cutting. Perfect for acrylic, wood, MDF, and metal projects.",
    capabilities: ["CO₂ & CNC laser cutting", "Acrylic, wood, MDF, leather", "Engraving on metal & glass", "Cutting area up to 600×400mm", "Custom stencils & signage"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "custom-drone",
    icon: "🚁",
    title: "Custom Drone Development",
    short: "End-to-end UAV design for photography, mapping, agriculture & research.",
    image: "/images/custom-drone.webp",
    category: "Service",
    desc: "End-to-end UAV design for research and industry.",
    overview: "We build custom drones for photography, mapping, surveillance, agriculture, and research. All drones are DGCA-compliant and performance-optimized for your specific use case.",
    capabilities: ["Photography & videography drones", "Agricultural spraying drones", "Survey & mapping UAVs", "DGCA compliant design", "Custom payload integration"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "rc-aircraft",
    icon: "✈️",
    title: "RC Aircraft Development",
    short: "Design, build and fly custom remote-controlled fixed-wing aircraft.",
    image: "/images/rc-aircraft.webp",
    category: "Service",
    desc: "Design and build remote controlled fixed-wing aircraft.",
    overview: "Hands-on service for building and flying RC aircrafts with aerodynamic design, remote configuration, and performance tuning support.",
    capabilities: ["Custom airframe design", "Aerodynamic optimization", "Flight controller integration", "Remote configuration", "Test flight support"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "rc-car",
    icon: "🏎️",
    title: "RC Car Development",
    short: "Custom RC car builds — high-performance vehicles for hobby and competition.",
    image: "/images/rc-car.webp",
    category: "Service",
    desc: "High-performance RC vehicles built to your spec.",
    overview: "Design, assemble, and control RC cars — blending speed, control, and engineering precision. Custom builds for hobby, competition, or research.",
    capabilities: ["Custom chassis design", "Brushless motor systems", "Suspension tuning", "Competition-grade builds", "Remote control programming"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "prototype",
    icon: "🧩",
    title: "Prototype Development",
    short: "From sketch to working hardware — PCB, firmware, 3D enclosures & testing.",
    image: "/images/pcb-prototype.webp",
    category: "Service",
    desc: "From sketch to working hardware prototype.",
    overview: "Turn your idea into a working hardware prototype. We provide end-to-end design, fabrication, PCB design, firmware development, and testing support.",
    capabilities: ["Concept to product development", "PCB design & fabrication", "Firmware & software development", "3D printed enclosures", "Testing & documentation"],
    pricing: "Discuss by call or WhatsApp",
  },
];

/* ── Engineering Projects ──────────────────────────────── */
export const projects = [
  {
    slug: "final-year",
    icon: "🎓",
    title: "Final Year Projects",
    desc: "Guided B.E. / B.Tech projects with documentation & demos.",
    overview: "We help engineering students conceptualize, design, build, and document their final year projects. From circuit design and coding to report writing and viva preparation — we are your project partner.",
    domains: ["IoT & Smart Systems", "Embedded Systems", "Robotics & Automation", "Drone-Based Projects", "AI & Machine Learning", "PCB Design"],
    deliverables: ["Working prototype", "Source code", "Circuit diagrams", "Project report", "PPT presentation", "Demo video"],
    sampleProjects: [
      "Smart Home Automation System",
      "GPS-based Vehicle Tracking",
      "Autonomous Line Following Robot",
      "IoT Weather Monitoring Station",
      "Gesture-Controlled Robot",
      "Smart Irrigation System",
      "RFID-based Attendance System",
      "Solar Energy Monitoring System",
    ],
  },
  {
    slug: "iot",
    icon: "🌐",
    title: "IoT Projects",
    desc: "Smart, connected hardware with cloud dashboards.",
    overview: "Smart IoT project development with cloud dashboards, sensors, and WiFi/Bluetooth connectivity. For students and professionals looking to build connected hardware solutions.",
    domains: ["Smart Home & Office", "Industrial IoT", "Agriculture IoT", "Healthcare IoT", "Environmental Monitoring"],
    deliverables: ["Working IoT device", "Cloud dashboard", "Mobile app integration", "Source code", "Documentation"],
    sampleProjects: [
      "Smart Home with Alexa Integration",
      "IoT-based Air Quality Monitor",
      "Smart Parking System",
      "Remote Health Monitoring",
      "Smart Agriculture with Soil Sensors",
    ],
  },
  {
    slug: "robotics",
    icon: "🦾",
    title: "Robotics Projects",
    desc: "Autonomous robots, robotic arms and more.",
    overview: "Custom robotics project development — autonomous bots, robotic arms, swarm robots, and competition robots with full mechanical, electronic, and software support.",
    domains: ["Autonomous Navigation", "Robotic Arms & Manipulators", "Swarm Robotics", "Competition Robots", "Medical Robotics"],
    deliverables: ["Working robot prototype", "3D printed parts", "Source code", "Technical documentation", "Demo video"],
    sampleProjects: [
      "6-DOF Robotic Arm",
      "Maze-Solving Robot",
      "Object Detection & Picking Robot",
      "Firefighting Robot",
      "Self-Balancing Robot",
    ],
  },
];

/* ── Testimonials ──────────────────────────────────────── */
export const testimonials = [
  {
    name: "Rahul Sharma",
    role: "Student, Class 10",
    quote: "Mech-E-Tron completely changed the way I think about technology. I built my first line-following robot within two weeks of joining, and the mentors made learning fun and easy!",
    rating: 5,
  },
  {
    name: "Priya Reddy",
    role: "Engineering Student",
    quote: "The Arduino UNO Learning Board is just amazing. I've completed more than 15 projects already, and I finally understand how sensors and circuits really work!",
    rating: 5,
  },
  {
    name: "Mrs. Lakshmi Devi",
    role: "Parent",
    quote: "My son participated in a robotics competition after learning at Mech-E-Tron and won second place! The hands-on sessions and guidance were excellent.",
    rating: 5,
  },
  {
    name: "Arjun Kumar",
    role: "Beginner Student",
    quote: "As a beginner, I was nervous about electronics. But the trainers explained every concept with real examples. Now I'm confident in coding and assembling small robots on my own.",
    rating: 5,
  },
  {
    name: "Dr. Anand Rao",
    role: "School Principal",
    quote: "Partnering with Mech-E-Tron for our school's STEM lab was one of the best decisions. Our students are now competing at state-level robotics events.",
    rating: 5,
  },
  {
    name: "Sneha Patel",
    role: "B.Tech Final Year",
    quote: "The final year project support was incredible. They helped me from ideation to documentation. My IoT project was appreciated by all the examiners.",
    rating: 5,
  },
];

/* ── Stats ─────────────────────────────────────────────── */
export const stats = [
  { value: "10,000+", label: "Students Trained" },
  { value: "120+", label: "Schools Partnered" },
  { value: "500+", label: "Projects Built" },
  { value: "50+", label: "Competitions" },
];

/* ── Company Info ──────────────────────────────────────── */
export const companyInfo = {
  name: "Mech-E-Tron",
  tagline: "Learn Robotics. Build the Future.",
  email: "info@mechetron.com",
  phone: "+91 8148435256",
  whatsapp: "918148435256",
  address: {
    line1: "Osmania Technology Business Incubator (OTBI)",
    line2: "Central Facilities for Research & Development Building",
    line3: "Osmania University, Hyderabad, Telangana, INDIA",
    pincode: "500007",
  },
  social: {
    instagram: "https://instagram.com/mechetron",
    youtube: "https://youtube.com/@mechetron",
    twitter: "https://twitter.com/mechetron",
  },
};

/* ── Navigation ────────────────────────────────────────── */
export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/courses", label: "Courses" },
  { href: "/services", label: "Services" },
  { href: "/projects", label: "Projects" },
  { href: "/schools", label: "For Schools" },
  { href: "/products/arduino-uno-learning-board", label: "Shop" },
  { href: "/gallery", label: "Gallery" },
  { href: "/about", label: "About" },
  { href: "/contact", label: "Contact" },
];

/* ── FAQ Data ──────────────────────────────────────────── */
export const courseFAQs = [
  { title: "What is the minimum age to join?", body: "Our Robotics Training and Arduino courses are open to students aged 10 and above. The Drone Workshop and Engineering Project support are ideal for students aged 14+ and college students." },
  { title: "Do I need prior coding experience?", body: "No prior experience is needed for the Robotics Training or Drone Workshop. The Arduino & Embedded Systems course starts from scratch — you'll learn C++ step by step through practical projects." },
  { title: "Are classes online or offline?", body: "We primarily run offline, hands-on sessions at our OTBI lab in Hyderabad. Online mentoring is available for final year engineering project support." },
  { title: "What is the batch size?", body: "We maintain a maximum 1:6 mentor-to-student ratio across all batches to ensure personalised attention." },
  { title: "Will I receive a certificate?", body: "Yes — all courses include a Certificate of Completion from Mech-E-Tron, recognised by our partner schools and institutions." },
  { title: "Are weekend batches available?", body: "Yes, weekend batches (Saturday & Sunday) are available for all courses and are the most popular option for school students." },
];

/* ── Blog Posts ─────────────────────────────────────────── */
export const blogPosts = [
  {
    slug: "5-reasons-child-learn-robotics",
    title: "5 Reasons Your Child Should Learn Robotics in 2026",
    excerpt: "Robotics isn't just for engineers anymore. Discover why every child should experience hands-on STEM learning.",
    date: "2026-03-15",
    category: "STEM Education",
    body: [
      "Robotics education is no longer a niche subject reserved for engineering colleges — it has become one of the most powerful tools for developing critical thinking, creativity, and problem-solving skills in children of all ages.",
      "**1. It makes abstract concepts tangible.** When a child programs a robot to avoid obstacles, they experience physics, logic, and mathematics in action. Concepts that are confusing on a whiteboard become crystal clear when the robot reacts to real-world inputs.",
      "**2. It builds persistence.** Debugging a robot that refuses to work correctly teaches children that failure is a step — not a stop. This growth mindset is one of the most valuable things a young person can develop.",
      "**3. It is the fastest path into technology careers.** India needs 1 million STEM professionals annually, and employers consistently cite hands-on experience as the differentiator between candidates. Starting at age 10–14 gives students years of head start.",
      "**4. It develops teamwork.** Most robotics challenges at Mech-E-Tron are collaborative. Students learn to divide tasks, communicate, and integrate their work — skills that matter in every professional context.",
      "**5. It is genuinely fun.** The most effective learning is joyful learning. Children who spend a Saturday building a Bluetooth-controlled car are not studying — they are playing with purpose.",
    ],
  },
  {
    slug: "arduino-vs-raspberry-pi",
    title: "Arduino vs. Raspberry Pi — Which Should Beginners Choose?",
    excerpt: "A practical comparison to help you pick the right platform for your first electronics project.",
    date: "2026-03-08",
    category: "Arduino",
    body: [
      "One of the most common questions we hear from beginners at Mech-E-Tron is: 'Should I start with Arduino or Raspberry Pi?' Both are excellent platforms, but they serve very different purposes.",
      "**Arduino: The hardware controller.** Arduino is a microcontroller — it runs a single program, controls physical hardware (motors, LEDs, sensors) in real time, and is extremely forgiving for beginners. It has no operating system, so there's nothing to crash. If you want to blink an LED, control a servo, or read a temperature sensor, Arduino is the right tool.",
      "**Raspberry Pi: The mini-computer.** Raspberry Pi runs a full Linux operating system. It can browse the web, run Python scripts, serve web pages, and process images. It's ideal for projects that need computing power — facial recognition, voice assistants, data dashboards.",
      "**Our recommendation for beginners: Start with Arduino.** The feedback loop is immediate and satisfying. Write five lines of code, see a motor turn. The simplicity removes barriers and builds confidence fast. Once you understand how hardware and software interact, graduating to Raspberry Pi becomes natural.",
      "At Mech-E-Tron, our Arduino & Embedded Systems course covers both platforms in the advanced modules, so students get exposure to both worlds with proper context.",
    ],
  },
  {
    slug: "choose-final-year-project",
    title: "How to Choose a Final Year Engineering Project",
    excerpt: "Tips and strategies for selecting a project that impresses your examiners and builds your portfolio.",
    date: "2026-02-25",
    category: "Projects",
    body: [
      "Your final year project is the single biggest opportunity in your undergraduate degree to demonstrate real engineering capability. Choosing the right project can define your portfolio for years.",
      "**Rule 1: Pick a problem, not a technology.** The best projects start with a real-world problem that needs solving — not 'I want to use machine learning.' Ask yourself: what inefficiency, danger, or cost can my project reduce? Examiners and employers are impressed by engineers who understand the value of what they build.",
      "**Rule 2: Ensure hardware + software integration.** A project that combines embedded firmware, physical sensors, and a cloud/mobile interface demonstrates breadth. Pure software projects are common; hardware-software integrations stand out.",
      "**Rule 3: Scope for 4–6 months.** Many students either overscope (AI drone swarm with autonomous mapping) or underscope (basic LED controller). Aim for something you can build to a working demo in 3 months, then spend the remaining time refining, documenting, and presenting.",
      "**Rule 4: Choose domains that are hiring.** IoT, robotics automation, and embedded systems are among the highest-demand engineering domains in India's 2026 job market. Projects in these areas attract attention from recruiters on placement day.",
      "At Mech-E-Tron, our project mentors help you ideate, scope, and deliver — from blank page to viva preparation.",
    ],
  },
  {
    slug: "top-robotics-competitions-india",
    title: "Top 10 Robotics Competitions in India for School Students",
    excerpt: "A curated list of the best robotics competitions that every young innovator should know about.",
    date: "2026-02-18",
    category: "Robotics",
    body: [
      "India has a growing and vibrant robotics competition ecosystem for school students. Competing is one of the fastest ways to accelerate learning, build confidence, and get noticed by colleges and employers.",
      "**1. WRO — World Robot Olympiad India:** The largest school robotics competition globally, with national qualifiers across India. Categories range from Regular (line-following, obstacle navigation) to Open (self-designed robots).",
      "**2. RoboLeague:** An annual inter-school robotics tournament with regional heats across major Indian cities. Events include sumo bots, maze solvers, and line-following challenges.",
      "**3. FIRST Lego League (FLL):** Combines Lego Mindstorms robotics with a research presentation component. One of the most prestigious competitions for students aged 9–14.",
      "**4. Smart India Hackathon (SIH) — School Edition:** Government-backed hackathon with categories for hardware and software innovations. Winning projects receive national recognition and mentorship.",
      "**5. TechFest (IIT Bombay):** Asia's largest science & technology festival. Multiple robotics events including Micromouse, Football Bots, and Robosoccer.",
      "Mech-E-Tron students regularly participate in WRO and RoboLeague, with dedicated competition coaching included in our Robotics Training course.",
    ],
  },
  {
    slug: "what-is-stem-education",
    title: "What is STEM Education and Why Does It Matter?",
    excerpt: "Understanding the STEM framework and its importance for India's next generation of innovators.",
    date: "2026-02-10",
    category: "STEM Education",
    body: [
      "STEM stands for Science, Technology, Engineering, and Mathematics. But the acronym undersells what STEM education really is: a philosophy of learning that prioritises doing over memorising, creating over consuming, and questioning over accepting.",
      "**Why traditional education falls short.** India's traditional curriculum excels at producing students who can recall information under examination conditions. It is less effective at producing students who can solve novel problems with incomplete information — which is exactly what every job in the 21st century requires.",
      "**What STEM education adds.** STEM programs introduce the engineering design cycle: identify a problem → research solutions → design → build → test → improve. This iterative process is how the real world works, and learning it early changes how students approach every challenge.",
      "**STEM and India's economic future.** India has set ambitious goals to become a global technology leader by 2030. Achieving this requires a pipeline of engineers, designers, and scientists who don't just know the theory but can build the products. STEM education from school level is the only way to create that pipeline at scale.",
      "At Mech-E-Tron, STEM is not a subject — it's the way we teach everything. Every course starts with a real problem and ends with a working solution that the student built themselves.",
    ],
  },
];

/* ── Site alias (backward compat for pages using `site`) ── */
export const site = {
  about:
    "Mech-E-Tron is India's hands-on robotics & STEM education platform — training the next generation of engineers through real robots, real code, and real projects. Founded in Hyderabad, we serve 10,000+ students and 120+ schools.",
  contact: {
    email: companyInfo.email,
    phone1: companyInfo.phone,
    phone2: "+91 7387996896",
    whatsapp: `https://wa.me/${companyInfo.whatsapp}?text=Hi%2C%20I%27m%20interested%20in%20Mech-E-Tron%20courses`,
    address: `${companyInfo.address.line1}, ${companyInfo.address.line2}, ${companyInfo.address.line3} — ${companyInfo.address.pincode}`,
  },
};

/* ── Arduino UNO Learning Board Product ─────────────────── */
export const arduinoProduct = {
  name: "Arduino UNO Learning Board",
  tagline: "One kit. 30+ projects. Infinite possibilities.",
  price: "₹1,799",
  mrp: "₹2,499",
  sku: "MET-ARD-UNO-01",
  image: "/images/arduino-kit.webp",
  images: [
    "/images/arduino-kit.webp",
    "/images/arduino-components.webp",
    "/images/pcb-prototype.webp",
  ],
  badge: "Best Seller",
  inStock: true,
  deliveryDays: "3–5 business days",
  whatsappOrder: "918148435256",
  description:
    "The Mech-E-Tron Arduino UNO Learning Board is a complete starter kit designed for students, hobbyists, and engineers who want to master embedded systems hands-on. Everything you need to complete 30+ real projects — straight out of the box.",
  features: [
    "Arduino UNO R3 — original ATmega328P microcontroller",
    "Breadboard (830 tie-point) for circuit prototyping",
    "Ultrasonic sensor (HC-SR04) for distance measurement",
    "IR sensor module for line following & object detection",
    "DHT11 temperature & humidity sensor",
    "LDR (Light Dependent Resistor) + 10kΩ resistors",
    "Servo motor (SG90) for motion control",
    "L298N motor driver module for DC motor control",
    "2× DC motors with wheels for robot builds",
    "16×2 LCD display with I2C module",
    "HC-05 Bluetooth module for wireless control",
    "Assorted LEDs, push buttons, resistors & jumper wires",
    "USB-A to USB-B cable for programming",
    "Project guide PDF — 30+ step-by-step projects",
  ],
  projects: [
    "Line Following Robot",
    "Obstacle Avoidance Robot",
    "Bluetooth-Controlled Car",
    "Smart Home Automation",
    "Temperature & Humidity Monitor",
    "Automatic Street Light",
    "Distance Measuring Device",
    "Servo Motor Controller",
    "LCD Display Projects",
    "LED Chaser & Patterns",
    "Push Button Counter",
    "Buzzer Alarm System",
    "PWM Speed Controller",
    "Digital Voltmeter",
    "Traffic Light Simulation",
    "Gesture-Controlled Robot",
    "IR Remote Control",
    "Soil Moisture Sensor",
    "Fire Detection Alarm",
    "Gas Leakage Detector",
    "Digital Thermometer",
    "Sound Detection System",
    "Clap Switch Circuit",
    "Rain Detector",
    "Pulse Rate Monitor (simulated)",
    "4-Digit 7-Segment Display",
    "RFID Reader Integration",
    "IoT Weather Station (with WiFi module)",
    "Joystick-Controlled Robot",
    "Stepper Motor Driver",
    "Real-Time Clock (RTC)",
    "Data Logger to SD Card",
  ],
  whyChoose: [
    { icon: "📦", title: "Everything Included", body: "No hunting for extra components — every part needed for all 30+ projects is in the box." },
    { icon: "📖", title: "Step-by-Step Guides", body: "Detailed PDF project guide with circuit diagrams, code, and explanations for every project." },
    { icon: "🔧", title: "Mentor Support", body: "Stuck? WhatsApp our team for free technical support for 3 months after purchase." },
    { icon: "🚀", title: "Scalable Learning", body: "Start with blinking LEDs — build up to an autonomous robot. The kit grows with you." },
    { icon: "🏆", title: "Used in Our Courses", body: "The same kit used in all Mech-E-Tron offline and online programs. Continuity guaranteed." },
  ],
};

/* ── Technologies Taught ────────────────────────────────── */
export const technologies = [
  { name: "Arduino IDE", icon: "⚡", color: "#00979D", desc: "Microcontroller programming" },
  { name: "Python", icon: "🐍", color: "#3776AB", desc: "NumPy · Pandas · OpenCV" },
  { name: "C / C++", icon: "💾", color: "#00599C", desc: "Embedded firmware & algorithms" },
  { name: "Embedded C", icon: "🔧", color: "#FF6A00", desc: "Low-level MCU programming" },
  { name: "Raspberry Pi", icon: "🍓", color: "#C51A4A", desc: "Linux-based projects & vision" },
  { name: "IoT & ESP32", icon: "🌐", color: "#0E7FD0", desc: "Connected hardware & MQTT" },
  { name: "MATLAB / Simulink", icon: "📊", color: "#E16737", desc: "Control systems & AI models" },
  { name: "FPGA / ARM Cortex", icon: "🖥️", color: "#7B2FBE", desc: "Advanced embedded architecture" },
  { name: "PCB Design", icon: "🔌", color: "#2ECC71", desc: "KiCad & EasyEDA schematic design" },
  { name: "3D Printing", icon: "🖨️", color: "#E74C3C", desc: "FDM prototyping & part design" },
  { name: "Drones / DGCA", icon: "🛸", color: "#0B3D91", desc: "UAV build, fly & compliance" },
];

/* ── Why Choose Mech-E-Tron ─────────────────────────────── */
export const whyChoose = [
  {
    icon: "🔩",
    title: "Practical, Hands-On Learning",
    body: "Every concept is taught on real hardware. No simulations — you build, break, and fix actual robots and circuits.",
    accent: "#FF6A00",
  },
  {
    icon: "👨‍🏫",
    title: "Expert Mentors",
    body: "Learn from industry engineers and educators with real-world experience in embedded systems, robotics, and drones.",
    accent: "#0B3D91",
  },
  {
    icon: "📦",
    title: "Arduino UNO Kit Included",
    body: "Every student gets our custom Arduino UNO Learning Board with 30+ project guides — yours to keep after the course.",
    accent: "#00979D",
  },
  {
    icon: "🏆",
    title: "Competition Training",
    body: "We train students for WRO, RoboLeague, AICRA, and Smart India Hackathon — with dedicated coaching and mock rounds.",
    accent: "#FFB400",
  },
  {
    icon: "🎓",
    title: "Recognized Certification",
    body: "Earn an industry-recognized certificate from OTBI-incubated Mech-E-Tron, trusted by 120+ schools across India.",
    accent: "#2ECC71",
  },
];

/* ── Gallery Items ──────────────────────────────────────── */
export const galleryItems = [
  {
    title: "Line Following Robot",
    student: "Rahul S.",
    category: "Robotics",
    image: "/images/robotics-lab.webp",
  },
  {
    title: "Obstacle Avoidance Bot",
    student: "Priya R.",
    category: "Robotics",
    image: "/images/arduino-components.webp",
  },
  {
    title: "Custom Photography Drone",
    student: "Arjun K.",
    category: "Drones",
    image: "/images/drone-flying.webp",
  },
  {
    title: "Smart Home IoT System",
    student: "Sneha P.",
    category: "IoT",
    image: "/images/iot-project.webp",
  },
  {
    title: "3D Printed Robot Chassis",
    student: "Vikram M.",
    category: "3D Printing",
    image: "/images/3d-printing.webp",
  },
  {
    title: "Arduino Weather Station",
    student: "Meera D.",
    category: "Arduino",
    image: "/images/arduino-kit.webp",
  },
  {
    title: "Bluetooth Car Controller",
    student: "Karthik N.",
    category: "Arduino",
    image: "/images/rc-car.webp",
  },
  {
    title: "Maze Solving Robot",
    student: "Ananya G.",
    category: "Robotics",
    image: "/images/stem-school.webp",
  },
];
