/* ── Courses ───────────────────────────────────────────── */
export const courses = [
  {
    slug: "arduino-uno-course",
    icon: "⚡",
    title: "Arduino UNO Course",
    short: "Master microcontrollers, sensors & C++ through hands-on project building.",
    image: "/images/arduino-kit.webp",
    category: "Course",
    desc: "15-day intensive course on Arduino, sensors, and basic circuits.",
    tag: "Popular",
    price: "₹2,999",
    duration: "15 Days",
    schedule: "1.5 Hours / Day (Mon–Sat)",
    level: "Beginner",
    audience: ["School students (6th–12th)", "Engineering students", "Hobbyists"],
    overview: "Master microcontrollers, sensors, and C++ through 3–5 hands-on mini projects. This course bridges the gap between hobby electronics and professional embedded design.",
    curriculum: [
      "Arduino Architecture & IDE Setup",
      "Digital & Analog I/O",
      "Sensor Integration (Ultrasonic, IR, etc.)",
      "Motor & Servo Control basics",
      "Building 3–5 Mini Projects",
    ],
    outcomes: [
      "Build 3–5 working mini projects",
      "Understand electronics & circuits",
      "Learn Arduino C++ programming",
      "Certificate of Completion",
    ],
  },
  {
    slug: "robotics-beginner-course",
    icon: "🤖",
    title: "Robotic Beginner Course",
    short: "Build real robots from scratch — mechanics, electronics & Arduino coding.",
    image: "/images/robotics-lab.webp",
    category: "Course",
    desc: "1-month comprehensive robotics training for beginners.",
    tag: "Hands-on",
    price: "₹3,999",
    duration: "1 Month",
    schedule: "1.5–2 Hours / Day (Mon–Sat)",
    level: "Beginner",
    audience: ["Students (10–18 years)", "Middle-class families", "Tech enthusiasts"],
    overview: "Learn mechanics, electronics, and coding by building real robots. Our focus is practical learning where students build real working models instead of just theory.",
    curriculum: [
      "Introduction to Robotic & Electronics",
      "Arduino Fundamentals & Programming",
      "Sensor Integration & Sensor Fusion",
      "Motor Control & Drive Systems",
      "Line Follower Robot Build",
      "Obstacle Avoidance Robot Build",
    ],
    outcomes: [
      "Build a Line Follower + Obstacle Avoidance robot",
      "Understand mechanical design & electronics",
      "Learn logic-based programming",
      "Certificate of Completion",
    ],
  },
  {
    slug: "ai-iot-training",
    icon: "🌐",
    title: "AI & IoT Training",
    short: "Smart, connected hardware integrated with Artificial Intelligence.",
    image: "/images/iot-project.webp",
    category: "Course",
    desc: "Advanced 2-month program on IoT, Cloud, and AI integration.",
    tag: "Advanced",
    price: "₹6,999",
    duration: "1.5 to 2 Months",
    schedule: "2 Hours / Day (Mon–Sat)",
    level: "Advanced",
    audience: ["Engineering students", "IT professionals", "IoT aspirants"],
    overview: "Deep-dive into the world of smart systems. Learn ESP32, MQTT, Cloud dashboards, and AI-based decision making for hardware.",
    curriculum: [
      "IoT Architecture & Network Protocols",
      "ESP32 & NodeMCU Programming",
      "Cloud Integration (Firebase / AWS IoT)",
      "Introduction to Small-Scale AI on Edge",
      "Developing Smart Home / AI-based Projects",
    ],
    outcomes: [
      "Build Smart IoT + AI-based projects",
      "Master cloud-to-hardware communication",
      "Real-world industry-relevant skills",
      "Certificate of Completion",
    ],
  },
  {
    slug: "drone-workshop",
    icon: "🛸",
    title: "Drone Workshop",
    short: "Build and fly your own quadcopter — from frame assembly to first flight.",
    image: "/images/drone-workshop.webp",
    category: "Course",
    desc: "Build, fly and program your own quadcopter drone.",
    tag: "Exciting",
    price: "₹2,500",
    duration: "2-Day Intensive",
    schedule: "4 Hours / Day",
    level: "All Levels",
    audience: ["Students & hobbyists", "Aspiring drone pilots", "Engineering students"],
    overview: "Experience the thrill of building a drone from scratch. Learn about aerodynamics, motor selection, flight controller programming, and DGCA compliance.",
    curriculum: [
      "Drone Anatomy & Aerodynamics",
      "Frame Assembly & Motor Configuration",
      "Flight Controller Setup",
      "Programming and GPS Integration",
      "First Flight & Calibration",
      "DGCA Guidelines & Safety",
    ],
    outcomes: [
      "Build a fully functional drone",
      "Understand flight dynamics",
      "DGCA awareness",
      "Certificate of Completion",
    ],
  },
];

/* ── Services ──────────────────────────────────────────── */
export const services = [
  {
    slug: "3d-printing",
    icon: "🖨️",
    title: "3D Printing",
    short: "High-precision FDM & resin printing for prototypes and project parts.",
    image: "/images/3d-printing.webp",
    category: "Service",
    desc: "Rapid prototyping with industrial-grade FDM & resin printers.",
    overview: "Bring your imagination to life with high-precision 3D printing. Perfect for prototypes, mechanical parts, and educational projects. We offer both FDM and resin printing with a wide range of materials.",
    capabilities: ["PLA, ABS, PETG, TPU materials", "Resin printing for fine detail", "Max build volume: 300×300×400mm", "Layer resolution down to 0.05mm", "Post-processing & finishing"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "laser-cutting",
    icon: "✂️",
    title: "Laser Cutting",
    short: "CO₂ & CNC precision cutting for acrylic, wood, MDF and more.",
    image: "/images/laser-cutting.webp",
    category: "Service",
    desc: "Precision cutting & engraving for acrylic, wood and more.",
    overview: "Achieve clean, precise, and intricate designs with advanced CNC and CO₂ laser cutting. Perfect for acrylic, wood, MDF, and metal projects.",
    capabilities: ["CO₂ & CNC laser cutting", "Acrylic, wood, MDF, leather", "Engraving on metal & glass", "Cutting area up to 600×400mm", "Custom stencils & signage"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "custom-drone",
    icon: "🚁",
    title: "Custom Drone Development",
    short: "End-to-end UAV design for photography, mapping, agriculture & research.",
    image: "/images/custom-drone.webp",
    category: "Service",
    desc: "End-to-end UAV design for research and industry.",
    overview: "We build custom drones for photography, mapping, surveillance, agriculture, and research. All drones are DGCA-compliant and performance-optimized for your specific use case.",
    capabilities: ["Photography & videography drones", "Agricultural spraying drones", "Survey & mapping UAVs", "DGCA compliant design", "Custom payload integration"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "rc-aircraft",
    icon: "✈️",
    title: "RC Aircraft Development",
    short: "Design, build and fly custom remote-controlled fixed-wing aircraft.",
    image: "/images/rc-aircraft.webp",
    category: "Service",
    desc: "Design and build remote controlled fixed-wing aircraft.",
    overview: "Hands-on service for building and flying RC aircrafts with aerodynamic design, remote configuration, and performance tuning support.",
    capabilities: ["Custom airframe design", "Aerodynamic optimization", "Flight controller integration", "Remote configuration", "Test flight support"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "rc-car",
    icon: "🏎️",
    title: "RC Car Development",
    short: "Custom RC car builds — high-performance vehicles for hobby and competition.",
    image: "/images/rc-car.webp",
    category: "Service",
    desc: "High-performance RC vehicles built to your spec.",
    overview: "Design, assemble, and control RC cars — blending speed, control, and engineering precision. Custom builds for hobby, competition, or research.",
    capabilities: ["Custom chassis design", "Brushless motor systems", "Suspension tuning", "Competition-grade builds", "Remote control programming"],
    pricing: "Discuss by call or WhatsApp",
  },
  {
    slug: "prototype",
    icon: "🧩",
    title: "Prototype Development",
    short: "From sketch to working hardware — PCB, firmware, 3D enclosures & testing.",
    image: "/images/pcb-prototype.webp",
    category: "Service",
    desc: "From sketch to working hardware prototype.",
    overview: "Turn your idea into a working hardware prototype. We provide end-to-end design, fabrication, PCB design, firmware development, and testing support.",
    capabilities: ["Concept to product development", "PCB design & fabrication", "Firmware & software development", "3D printed enclosures", "Testing & documentation"],
    pricing: "Discuss by call or WhatsApp",
  },
];

/* ── Engineering Projects ──────────────────────────────── */
export const projects = [
  {
    slug: "btech-final-year",
    icon: "🎓",
    title: "Final Year Project (B.Tech)",
    desc: "Complete hardware & software support for B.Tech aspirants.",
    price: "₹8,000 min (varies as per project)",
    duration: "30–45 Days",
    overview: "We help B.Tech students conceptualize, design, and build industry-standard final year projects with full support for hardware, code, and documentation.",
    support: ["Hardware Provided", "Source Code", "Detailed Project Report", "Viva & Presentation Prep"],
    domains: ["IoT & Smart Systems", "Robotic & Automation", "Embedded Systems", "AI & Machine Learning", "Drone Technology"],
    deliverables: ["Working prototype", "Source code", "Circuit diagrams", "Project report", "PPT presentation", "Demo video"],
    sampleProjects: [
      "Smart Home Automation with Alexa",
      "GPS-based Vehicle Tracking & Locking",
      "Autonomous Warehouse Robot",
      "IoT Weather Monitoring System",
      "Gesture-Controlled Assistive Bot",
      "Smart Parking with RFID",
    ],
  },
  {
    slug: "mtech-final-year",
    icon: "🏛️",
    title: "Final Year Project (M.Tech)",
    desc: "Advanced research-oriented project development and documentation.",
    price: "₹12,000 min (varies as per project)",
    duration: "45–60 Days",
    overview: "Advanced implementation and research-level documentation for M.Tech students. Focus on innovative solutions and technical depth.",
    support: ["Advanced implementation", "Research-level documentation", "Paper guidance (optional)", "Viva support"],
    domains: ["High-end Robotic", "Research-level AI/ML", "Advanced Communication Systems", "Industrial Automation"],
    deliverables: ["Advanced working prototype", "Optimized code", "Research documentation", "Publication support (optional)"],
    sampleProjects: [
      "Swarm Robotic Coordination",
      "FPGA-based Real-time Signal Processor",
      "Autonomous Drone with OpenCV Mapping",
      "Advanced PLC-based Industrial Automation",
      "Predictive Maintenance using TinyML",
      "Deep Learning for Medical Robotic",
    ],
  },
];

/* ── Summer Camp ────────────────────────────────────────── */
export const summerCamp = {
  title: "Robotic Summer Camp 2026",
  tagline: "Build Your Own Working Robot This Summer",
  price: "₹2,299",
  duration: "15 or 30 Days",
  schedule: "2–3 Hours / Day (Mon–Sat)",
  outcome: "Build working robot + Certificate",
  batches: [
    { id: 1, name: "Batch 1", dates: "May 1 – May 15" },
    { id: 2, name: "Batch 2", dates: "May 16 – May 30" },
    { id: 3, name: "Batch 3", dates: "Jun 1 – Jun 15" },
    { id: 4, name: "Batch 4", dates: "Jun 16 – Jun 30" },
  ],
  timings: [
    { id: 1, label: "Option 1", time: "10:00 AM – 1:00 PM" },
    { id: 2, label: "Option 2", time: "2:00 PM – 5:00 PM" },
  ],
  locations: [
    { name: "Chennai", capacity: "40 Seats Total", perBatch: "20 per batch" },
    { name: "Hyderabad", capacity: "40 Seats Total", perBatch: "20 per batch" },
    { name: "Tirupati (AP)", capacity: "40 Seats Total", perBatch: "20 per batch" },
  ],
  features: [
    "Hands-on hardware building",
    "Robotic kits included for use",
    "Small batches (10–20 students)",
    "Certification from Mech-E-Tron",
    "Fun, innovative learning environment",
  ],
};

/* ── Testimonials ──────────────────────────────────────── */
export const testimonials = [
  {
    name: "Rahul Sharma",
    role: "Student, Class 10",
    quote: "Mech-ε-Tron completely changed the way I think about technology. I built my first line-following robot within two weeks of joining, and the mentors made learning fun and easy!",
    rating: 5,
  },
  {
    name: "Priya Reddy",
    role: "Engineering Student",
    quote: "The Arduino UNO Learning Board is just amazing. I've completed more than 15 projects already, and I finally understand how sensors and circuits really work!",
    rating: 5,
  },
  {
    name: "Mrs. Lakshmi Devi",
    role: "Parent",
    quote: "My son participated in a robotics competition after learning at Mech-ε-Tron and won second place! The hands-on sessions and guidance were excellent.",
    rating: 5,
  },
  {
    name: "Arjun Kumar",
    role: "Beginner Student",
    quote: "As a beginner, I was nervous about electronics. But the trainers explained every concept with real examples. Now I'm confident in coding and assembling small robots on my own.",
    rating: 5,
  },
  {
    name: "Dr. Anand Rao",
    role: "School Principal",
    quote: "Partnering with Mech-E-Tron for our school's STEM lab was one of the best decisions. Our students are now competing at state-level robotics events.",
    rating: 5,
  },
  {
    name: "Sneha Patel",
    role: "B.Tech Final Year",
    quote: "The final year project support was incredible. They helped me from ideation to documentation. My IoT project was appreciated by all the examiners.",
    rating: 5,
  },
];

/* ── Stats ─────────────────────────────────────────────── */
export const stats = [
  { value: "10,000+", label: "Students Trained" },
  { value: "120+", label: "Schools Partnered" },
  { value: "500+", label: "Projects Built" },
  { value: "50+", label: "Competitions" },
];

/* ── Company Info ──────────────────────────────────────── */
export const companyInfo = {
  name: "MECH-ε-TRON™",
  logoNavbar: "/images/logo-navbar.png",
  logoFooter: "/images/logo-footer.png",
  tagline: "Build Skills, Not Just Theory.",
  email: "info@mechetron.com",
  phone: "+91 81484 35246",
  phone2: "+91 84999 85383",
  whatsapp: "918148435246",
  address: {
    line1: "OTBI, OU, Central Facilities for Research & Development Building",
    line2: "Osmania University",
    line3: "Hyderabad, Telangana",
    pincode: "500007",
  },
  locations: [
    {
      city: "Hyderabad",
      address: "OTBI, OU, Osmania University",
      state: "Telangana",
      pincode: "500007",
    },
    {
      city: "Chennai",
      address: "Mahindra World City, Paranur railway station",
      state: "Tamil Nadu",
      pincode: "603002",
    },
    {
      city: "Tirupati",
      address: "Upcoming Training Center",
      state: "Andhra Pradesh",
      pincode: "517501",
    },
  ],
  social: {
    instagram: "https://instagram.com/mechetron",
    youtube: "https://youtube.com/@mechetron",
    twitter: "https://twitter.com/mechetron",
  },
  affiliations: [
    "AICRA District Coordinator",
    "MSME Registered & ISO Certified",
    "Skill India (YTD)",
    "Training by Retired Indian Air Force Officers",
  ],
};

/* ── Navigation ────────────────────────────────────────── */
export const navLinks = [
  {
    href: "/courses",
    label: "Courses",
    children: [
      { href: "/courses/arduino-uno-course",      label: "Arduino UNO" },
      { href: "/courses/robotics-beginner-course", label: "Robotics Program" },
      { href: "/courses/ai-iot-training",          label: "AI & IoT" },
      { href: "/courses/drone-workshop",           label: "Drone Workshop" },
      { href: "/summer-camp",                      label: "Summer Camp" },
      { href: "/stem-modules",                     label: "STEM Modules" },
      { href: "/wooden-diy",                       label: "Wooden DIY Kits" },
    ],
  },
  {
    href: "/services",
    label: "Services",
    children: [
      { href: "/services/3d-printing",     label: "3D Printing" },
      { href: "/services/laser-cutting",   label: "Laser Cutting" },
      { href: "/services/custom-drone",    label: "Custom Drone" },
      { href: "/projects/btech-final-year",label: "Final Year Projects" },
    ],
  },
  { href: "/schools", label: "Schools" },
  {
    href: "/about",
    label: "About",
    children: [
      { href: "/about",   label: "About Us" },
      { href: "/gallery", label: "Gallery" },
    ],
  },
  { href: "/contact", label: "Contact" },
];

/* ── FAQ Data ──────────────────────────────────────────── */
export const courseFAQs = [
  { title: "What is the minimum age to join?", body: "Our Robotic Training and Arduino courses are open to students aged 10 and above. The Drone Workshop and Engineering Project support are ideal for students aged 14+ and college students." },
  { title: "Do I need prior coding experience?", body: "No prior experience is needed for the Robotic Training or Drone Workshop. The Arduino & Embedded Systems course starts from scratch — you'll learn C++ step by step through practical projects." },
  { title: "Are classes online or offline?", body: "We primarily run offline, hands-on sessions at our OTBI lab in Hyderabad. Online mentoring is available for final year engineering project support." },
  { title: "What is the batch size?", body: "We maintain a maximum 1:6 mentor-to-student ratio across all batches to ensure personalised attention." },
  { title: "Will I receive a certificate?", body: "Yes — all courses include a Certificate of Completion from Mech-E-Tron, recognised by our partner schools and institutions." },
  { title: "Are weekend batches available?", body: "Yes, weekend batches (Saturday & Sunday) are available for all courses and are the most popular option for school students." },
];

/* ── Blog Posts ─────────────────────────────────────────── */
export const blogPosts = [
  {
    slug: "5-reasons-child-learn-robotics",
    title: "5 Reasons Your Child Should Learn Robotic in 2026",
    excerpt: "Robotic isn't just for engineers anymore. Discover why every child should experience hands-on STEM learning.",
    date: "2026-03-15",
    category: "STEM Education",
    image: "/images/robotics-lab.webp",
    body: [
      "Robotic education is no longer a niche subject reserved for engineering colleges — it has become one of the most powerful tools for developing critical thinking, creativity, and problem-solving skills in children of all ages.",
      "**1. It makes abstract concepts tangible.** When a child programs a robot to avoid obstacles, they experience physics, logic, and mathematics in action. Concepts that are confusing on a whiteboard become crystal clear when the robot reacts to real-world inputs.",
      "**2. It builds persistence.** Debugging a robot that refuses to work correctly teaches children that failure is a step — not a stop. This growth mindset is one of the most valuable things a young person can develop.",
      "**3. It is the fastest path into technology careers.** India needs 1 million STEM professionals annually, and employers consistently cite hands-on experience as the differentiator between candidates. Starting at age 10–14 gives students years of head start.",
      "**4. It develops teamwork.** Most robotics challenges at Mech-E-Tron are collaborative. Students learn to divide tasks, communicate, and integrate their work — skills that matter in every professional context.",
      "**5. It is genuinely fun.** The most effective learning is joyful learning. Children who spend a Saturday building a Bluetooth-controlled car are not studying — they are playing with purpose.",
    ],
  },
  {
    slug: "arduino-vs-raspberry-pi",
    title: "Arduino vs. Raspberry Pi — Which Should Beginners Choose?",
    excerpt: "A practical comparison to help you pick the right platform for your first electronics project.",
    date: "2026-03-08",
    category: "Arduino",
    image: "/images/arduino-kit.webp",
    body: [
      "One of the most common questions we hear from beginners at Mech-E-Tron is: 'Should I start with Arduino or Raspberry Pi?' Both are excellent platforms, but they serve very different purposes.",
      "**Arduino: The hardware controller.** Arduino is a microcontroller — it runs a single program, controls physical hardware (motors, LEDs, sensors) in real time, and is extremely forgiving for beginners. It has no operating system, so there's nothing to crash. If you want to blink an LED, control a servo, or read a temperature sensor, Arduino is the right tool.",
      "**Raspberry Pi: The mini-computer.** Raspberry Pi runs a full Linux operating system. It can browse the web, run Python scripts, serve web pages, and process images. It's ideal for projects that need computing power — facial recognition, voice assistants, data dashboards.",
      "**Our recommendation for beginners: Start with Arduino.** The feedback loop is immediate and satisfying. Write five lines of code, see a motor turn. The simplicity removes barriers and builds confidence fast. Once you understand how hardware and software interact, graduating to Raspberry Pi becomes natural.",
      "At Mech-E-Tron, our Arduino & Embedded Systems course covers both platforms in the advanced modules, so students get exposure to both worlds with proper context.",
    ],
  },
  {
    slug: "choose-final-year-project",
    title: "How to Choose a Final Year Engineering Project",
    excerpt: "Tips and strategies for selecting a project that impresses your examiners and builds your portfolio.",
    date: "2026-02-25",
    category: "Projects",
    image: "/images/iot-project.webp",
    body: [
      "Your final year project is the single biggest opportunity in your undergraduate degree to demonstrate real engineering capability. Choosing the right project can define your portfolio for years.",
      "**Rule 1: Pick a problem, not a technology.** The best projects start with a real-world problem that needs solving — not 'I want to use machine learning.' Ask yourself: what inefficiency, danger, or cost can my project reduce? Examiners and employers are impressed by engineers who understand the value of what they build.",
      "**Rule 2: Ensure hardware + software integration.** A project that combines embedded firmware, physical sensors, and a cloud/mobile interface demonstrates breadth. Pure software projects are common; hardware-software integrations stand out.",
      "**Rule 3: Scope for 4–6 months.** Many students either overscope (AI drone swarm with autonomous mapping) or underscope (basic LED controller). Aim for something you can build to a working demo in 3 months, then spend the remaining time refining, documenting, and presenting.",
      "**Rule 4: Choose domains that are hiring.** IoT, robotics automation, and embedded systems are among the highest-demand engineering domains in India's 2026 job market. Projects in these areas attract attention from recruiters on placement day.",
      "At Mech-E-Tron, our project mentors help you ideate, scope, and deliver — from blank page to viva preparation.",
    ],
  },
  {
    slug: "top-robotics-competitions-india",
    title: "Top 10 Robotic Competitions in India for School Students",
    excerpt: "A curated list of the best robotics competitions that every young innovator should know about.",
    date: "2026-02-18",
    category: "Robotic",
    image: "/images/robotics-lab.webp",
    body: [
      "India has a growing and vibrant robotics competition ecosystem for school students. Competing is one of the fastest ways to accelerate learning, build confidence, and get noticed by colleges and employers.",
      "**1. WRO — World Robot Olympiad India:** The largest school robotics competition globally, with national qualifiers across India. Categories range from Regular (line-following, obstacle navigation) to Open (self-designed robots).",
      "**2. RoboLeague:** An annual inter-school robotics tournament with regional heats across major Indian cities. Events include sumo bots, maze solvers, and line-following challenges.",
      "**3. FIRST Lego League (FLL):** Combines Lego Mindstorms robotics with a research presentation component. One of the most prestigious competitions for students aged 9–14.",
      "**4. Smart India Hackathon (SIH) — School Edition:** Government-backed hackathon with categories for hardware and software innovations. Winning projects receive national recognition and mentorship.",
      "**5. TechFest (IIT Bombay):** Asia's largest science & technology festival. Multiple robotics events including Micromouse, Football Bots, and Robosoccer.",
      "Mech-E-Tron students regularly participate in WRO and RoboLeague, with dedicated competition coaching included in our Robotic Training course.",
    ],
  },
  {
    slug: "what-is-stem-education",
    title: "What is STEM Education and Why Does It Matter?",
    excerpt: "Understanding the STEM framework and its importance for India's next generation of innovators.",
    date: "2026-02-10",
    category: "STEM Education",
    image: "/images/classroom.webp",
    body: [
      "STEM stands for Science, Technology, Engineering, and Mathematics. But the acronym undersells what STEM education really is: a philosophy of learning that prioritises doing over memorising, creating over consuming, and questioning over accepting.",
      "**Why traditional education falls short.** India's traditional curriculum excels at producing students who can recall information under examination conditions. It is less effective at producing students who can solve novel problems with incomplete information — which is exactly what every job in the 21st century requires.",
      "**What STEM education adds.** STEM programs introduce the engineering design cycle: identify a problem → research solutions → design → build → test → improve. This iterative process is how the real world works, and learning it early changes how students approach every challenge.",
      "**STEM and India's economic future.** India has set ambitious goals to become a global technology leader by 2030. Achieving this requires a pipeline of engineers, designers, and scientists who don't just know the theory but can build the products. STEM education from school level is the only way to create that pipeline at scale.",
      "At Mech-E-Tron, STEM is not a subject — it's the way we teach everything. Every course starts with a real problem and ends with a working solution that the student built themselves.",
      "**Frequently Asked Questions**",
      "**Q: What age should children start STEM education?** A: We recommend starting as early as Grade 3 (age 8). Our Summer Camp is designed for Grade 3–9 and provides an ideal first exposure to robotics and engineering thinking.",
      "**Q: Does STEM education help in board exams?** A: Yes — students who engage in practical STEM activities consistently demonstrate stronger performance in Physics, Mathematics and Computer Science because they understand why concepts work, not just what they are.",
      "**Q: Is Mech-E-Tron STEM education affordable?** A: Our Summer Camp starts at ₹2,299 for 15 days. Our Arduino UNO Course is ₹2,999 for 15 days. These are among the most competitive prices in India for certified STEM training.",
    ],
  },
  {
    slug: "how-to-build-line-follower-robot",
    title: "How to Build a Line Follower Robot with Arduino — Step by Step Guide",
    excerpt: "Complete step-by-step guide to building a line follower robot using Arduino UNO, IR sensors and L298N motor driver.",
    date: "2026-03-20",
    category: "Arduino",
    image: "/images/robotics-lab.webp",
    body: [
      "A line follower robot is one of the most rewarding first projects in robotics education — and it teaches you more about sensors, motor control, and real-time decision making than almost any other beginner build. This guide will take you from zero to a working robot.",
      "**Components You Need**\nArduino UNO × 1, IR Sensor Module × 2, L298N Motor Driver Module × 1, DC Gear Motors × 2, Robot Chassis with wheels, 7.4V LiPo battery or 6×AA battery pack, jumper wires, and a black electrical tape track on white surface.",
      "**How It Works**\nIR sensors emit infrared light and detect whether it reflects back. Black tape absorbs IR light (sensor reads HIGH), white surface reflects it (sensor reads LOW). The Arduino reads both sensors and steers the robot to stay on the line: if left sensor detects black, turn left; if right sensor detects black, turn right; if both see white, go straight.",
      "**Wiring the Circuit**\nConnect the L298N ENA to Arduino pin 5 (PWM), IN1 to pin 6, IN2 to pin 7, ENB to pin 10 (PWM), IN3 to pin 8, IN4 to pin 9. Left IR sensor OUT to Arduino pin 2, Right IR sensor OUT to pin 3. Power the L298N from your battery; connect L298N 5V output to Arduino VIN.",
      "**The Code (simplified)**\nRead both IR sensors each loop. If leftSensor is HIGH and rightSensor is LOW, turn left by reversing the right motor. If rightSensor is HIGH and leftSensor is LOW, turn right. If both are LOW (on white), go full speed ahead. If both are HIGH (junction or end), stop or slow down.",
      "**Troubleshooting Tips**\nRobot oscillates wildly: your motors are too fast — reduce PWM speed from 255 to 150. Robot doesn't follow curves: increase sensor sensitivity using the blue potentiometer on the IR module. Robot overshoots turns: add a small delay (5–10ms) when turning.",
      "**FAQ**",
      "**Q: What if I have 3 IR sensors?** A: With 3 sensors, use the middle one as the baseline. If left sensor HIGH → turn left, right sensor HIGH → turn right, middle only → go straight. This gives smoother tracking.",
      "**Q: Can I use L293D instead of L298N?** A: Yes. The L293D is smaller and fine for light robots, but can only supply 600mA per channel. For heavier robots, stick with L298N.",
      "**Q: How fast should the robot go?** A: For beginners, set PWM to 120–150 (out of 255). This gives you time to debug. Speed up gradually once the logic works.",
      "**Q: What track width works best?** A: Use 2cm wide black electrical tape with at least 5cm white border on each side. Curves should have a minimum radius of 15cm for a standard chassis.",
      "**Q: Does this work at night?** A: IR sensors are not affected by darkness, but bright sunlight can interfere. Calibrate sensors indoors first.",
      "Learn to build this exact robot in Week 1 of our **Robotics Beginner Course at Mech-E-Tron** — available in Chennai, Hyderabad and Tirupati. Our course covers line follower, obstacle avoidance robot, and 4 more builds in one month. Enrol at mechetron.com/courses/robotics-beginner-course.",
    ],
  },
  {
    slug: "best-robotics-courses-chennai",
    title: "Best Robotics Courses in Chennai 2026 — Hands-On STEM Training",
    excerpt: "A complete guide to finding the best robotics courses in Chennai for school students and engineering professionals.",
    date: "2026-03-22",
    category: "STEM Education",
    image: "/images/classroom.webp",
    body: [
      "Chennai is rapidly becoming one of India's most important technology education hubs. With the city's growing engineering college ecosystem and strong demand from schools, **robotics courses in Chennai** have never been more relevant — or more sought-after.",
      "**Why Chennai Students Need Robotics Skills**\nChennai houses some of India's top engineering colleges and a dense cluster of manufacturing and technology companies. Students who graduate with hands-on robotics and embedded systems experience consistently land better placements and internships. Beyond careers, robotics builds the kind of problem-solving, teamwork, and creativity that no textbook can teach.",
      "**What Makes a Good Robotics Course?**\nThe single biggest differentiator between robotics programs is whether you actually build things. Theory-only courses teach you to draw circuit diagrams. Good courses put a soldering iron and a motor driver in your hands on Day 1. Look for: hands-on project ratio (minimum 60% practical), small batch sizes (max 1:8 mentor-to-student), recognized certification, and real components — not simulations.",
      "**Mech-E-Tron Chennai — What We Offer**\nOur Chennai center is located at Mahindra World City, Paranur (near Paranur Railway Station, PIN 603002) — accessible from across the city. We run four core programs:\n- **Arduino UNO Course**: 15 days, ₹2,999. Build 3–5 mini projects from scratch.\n- **Robotics Beginner Course**: 1 month, ₹3,999. Build a line follower and obstacle avoidance robot.\n- **AI & IoT Training**: 2 months, ₹6,999. ESP32, Firebase, cloud dashboards.\n- **Summer Camp** (Grade 3–9): 15 days, ₹2,299. Free robotic kit included.",
      "**Our Unique Advantages**\nWe are proud to be an **AICRA District Coordinator** — one of a limited number of institutes authorised to issue AICRA robotics certificates, which are recognised by schools and institutions nationwide. Our drone training is delivered by a **retired Indian Air Force officer** — a standard no other centre in Chennai can match. We are also MSME registered and ISO certified.",
      "**Student Success Stories**\nOur students have competed and won at state and national WRC (World Robotics Championship) events. Several of our B.Tech project students have received distinction grades, and our Arduino kit graduates have gone on to build their own products and startups.",
      "**FAQ — Robotics Courses in Chennai**",
      "**Q: What is the minimum age to join?** A: Our Summer Camp accepts students from Grade 3 (age ~8). The Arduino and Robotics courses are ideal from Grade 6 (age ~11) onwards.",
      "**Q: Are classes offline or online?** A: All practical courses are offline at our Chennai center. Final year project mentoring has an online option.",
      "**Q: Do I need prior electronics experience?** A: No. All courses start from absolute basics. Our Arduino course begins with 'what is electricity' before touching code.",
      "**Q: What certificate do I get?** A: An AICRA Certificate of Completion, recognized across India. Some courses also include a Mech-E-Tron certificate.",
      "**Q: Are weekend batches available?** A: Yes. Saturday–Sunday batches are our most popular option for school students.",
      "Ready to join the best robotics course in Chennai? **Book a free demo** at Mech-E-Tron's Chennai center. Visit mechetron.com/contact or WhatsApp +91 8148435246.",
    ],
  },
  {
    slug: "final-year-project-ideas-ece",
    title: "Top 10 Final Year Project Ideas for ECE Students Using Arduino and IoT",
    excerpt: "10 detailed final year project ideas for ECE, EEE and CSE students with components list and why examiners love each one.",
    date: "2026-03-18",
    category: "Projects",
    image: "/images/iot-project.webp",
    body: [
      "Choosing the right final year project can define your entire undergraduate reputation. After helping hundreds of B.Tech and M.Tech students across ECE, EEE, and CSE branches, we've identified the projects that consistently impress examiners, attract placement offers, and are actually achievable in 30–45 days.",
      "**Project 1 — Smart Home Automation System** (Difficulty: ⭐⭐⭐)\nComponents: Arduino UNO, ESP8266 WiFi module, relay modules ×4, DHT11 sensor, smartphone. What it does: controls lights, fans and appliances via mobile app. Why judges love it: combines IoT, embedded systems, and user interface design — three domains in one project.",
      "**Project 2 — Line Follower Robot with PID Control** (Difficulty: ⭐⭐⭐)\nComponents: Arduino, IR sensors ×5, L298N, DC motors. What it does: follows a line path using PID algorithm for smooth tracking. Why judges love it: PID implementation demonstrates advanced control theory, which is rarely seen in undergraduate projects.",
      "**Project 3 — IoT Weather Monitoring Station** (Difficulty: ⭐⭐)\nComponents: ESP32, DHT22, BMP180, OLED display, Blynk/Firebase. What it does: monitors temperature, humidity, pressure and uploads to cloud dashboard. Why judges love it: clean real-world application with cloud integration and data visualization.",
      "**Project 4 — RFID-Based Attendance System** (Difficulty: ⭐⭐)\nComponents: Arduino, RFID RC522 module, LCD display, SD card module. What it does: automated attendance logging using RFID cards. Why judges love it: directly solves an institutional problem, shows real-world deployment thinking.",
      "**Project 5 — Gesture Controlled Robot** (Difficulty: ⭐⭐⭐⭐)\nComponents: Arduino ×2, MPU6050 accelerometer, nRF24L01 RF module, DC motors. What it does: robot mirrors hand movements via wrist-worn glove sensor. Why judges love it: wireless communication plus sensor fusion is impressive hardware integration.",
      "**Project 6 — Smart Agriculture System** (Difficulty: ⭐⭐⭐)\nComponents: ESP32, soil moisture sensor, DHT11, water pump, relay, Blynk. What it does: auto-waters plants when soil is dry, sends alerts to phone. Why judges love it: Government of India's focus on agri-tech makes this highly relevant.",
      "**Project 7 — Obstacle Avoidance Autonomous Robot** (Difficulty: ⭐⭐)\nComponents: Arduino, HC-SR04 ultrasonic sensors ×3, servo motor, L298N, DC motors. What it does: navigates without hitting obstacles. Why judges love it: clear demonstration of sensor fusion and real-time decision making.",
      "**Project 8 — GPS Vehicle Tracking System** (Difficulty: ⭐⭐⭐)\nComponents: Arduino, SIM800L GSM module, GPS NEO-6M, Google Maps API. What it does: real-time vehicle location on phone or web dashboard. Why judges love it: commercially relevant, combines hardware with web/mobile layer.",
      "**Project 9 — Fire Detection and Alarm System** (Difficulty: ⭐⭐)\nComponents: Arduino, flame sensor, MQ-2 gas sensor, buzzer, GSM module. What it does: detects fire/smoke and sends SMS alert while triggering alarm. Why judges love it: safety application with immediate real-world value.",
      "**Project 10 — Smart Street Light with Auto-Dimming** (Difficulty: ⭐⭐⭐)\nComponents: Arduino, LDR sensor, PIR motion sensor, relay, LED array. What it does: auto-brightens when motion detected, dims otherwise, logs power savings. Why judges love it: energy efficiency project with data-backed results is highly valued by government and industry.",
      "**FAQ — Final Year Projects**",
      "**Q: How long does a complete project take?** A: With full support, 30–45 days from concept to report. Our B.Tech support package covers hardware, code, circuit diagram, report, and viva preparation.",
      "**Q: What if my project doesn't work on viva day?** A: We provide demo video documentation and backup components so you're never stranded on the day.",
      "**Q: Can I do a project from a different domain?** A: Yes. We support Mechanical, Civil, CSE, and EEE projects beyond ECE. Call us to discuss.",
      "Need complete project support? **Mech-E-Tron provides hardware, code, project report and viva preparation starting from ₹8,000.** Contact us at mechetron.com/contact or call +91 8148435246.",
    ],
  },
  {
    slug: "robotics-summer-camp-guide",
    title: "Robotics Summer Camp for Kids 2026 — Complete Parent Guide",
    excerpt: "Everything parents need to know about robotics summer camps in India — what children learn, what to expect, and why it matters.",
    date: "2026-03-25",
    category: "STEM Education",
    image: "/images/classroom.webp",
    body: [
      "Every summer, thousands of Indian parents ask the same question: should I let my child sit in front of screens all vacation, or is there something more valuable they could be doing? A **robotics summer camp** is one of the most powerful investments you can make in a child's future — and this guide tells you everything you need to know.",
      "**Why Summer Camps Matter for Skill Development**\nThe Indian school curriculum, despite recent improvements, leaves little room for creativity, hands-on experimentation, or failure-based learning. Summer is the only time children have enough unstructured hours to truly explore. A well-designed robotics camp fills that space with purposeful, joyful learning that builds skills schools simply can't teach.",
      "**What Children Learn in 15 Days**\nIn Mech-E-Tron's Summer Camp, students in Grade 3–9 progress through: basic electronics and circuit theory, Arduino programming (no prior coding needed), sensor integration (ultrasonic, IR, temperature), motor control, and culminate in building their own working robot. Students leave with the robot they built, an AICRA certificate, and a confidence in technology that changes how they approach school subjects.",
      "**What a Typical Camp Day Looks Like**\n9:00 AM or 2:00 PM — Students arrive at the lab. First 30 minutes: concept session with visual demonstrations. Next 90 minutes: hands-on build time with 1:6 mentor ratio. Final 30 minutes: testing, debugging, and documentation. Students never watch a video when they could be holding a component.",
      "**Age Group Guidance**\nGrade 3–5 (ages 8–10): Focus on basic circuits, LED projects, and simple Arduino sketches. Grade 6–7 (ages 11–12): Sensor integration, motor control, simple robots. Grade 8–9 (ages 13–14): Full robot build including line follower or obstacle avoidance. All groups work together in mixed-age sessions where older students mentor younger ones.",
      "**What the Free Kit Includes**\nEvery registered student receives: Arduino UNO compatible board, USB cable, breadboard, LED assortment (20 pcs), resistor kit, jumper wire pack, and a project reference card. This kit is theirs to keep — we believe children learn most when they can experiment at home after camp.",
      "**The AICRA Certificate**\nAICRA (All India Council for Robotics & Automation) is the national body for robotics education in India. Their certificate is recognised by schools, engineering colleges, and employers. Many schools award extra marks for AICRA certifications, and engineering colleges view them favorably during admissions.",
      "**Batch Details for 2026**\nBatch 1: May 1–15 | Batch 2: May 16–30 | Batch 3: June 1–15 | Batch 4: June 16–30. Timings: 10:00 AM–1:00 PM or 2:00 PM–5:00 PM. Maximum 20 students per batch to ensure quality. Locations: Chennai (Mahindra World City, Paranur) and Hyderabad (OTBI, Osmania University).",
      "**FAQ for Parents**",
      "**Q: My child has never touched electronics. Is this camp suitable?** A: Absolutely. The camp is designed for complete beginners. Our mentors explain everything from first principles.",
      "**Q: What if my child falls behind or gets confused?** A: Our 1:6 mentor-to-student ratio means every child gets personal attention. No child is left behind in our sessions.",
      "**Q: Is the camp safe? What safety measures are used?** A: All components operate at 5V — completely safe for children. No soldering in Grade 3–5 groups. Safety goggles and guidance provided throughout.",
      "**Q: What happens after the camp ends?** A: Students join our WhatsApp alumni group where mentors answer questions. Many students continue with our Arduino or Robotics courses at discounted rates.",
      "**Q: Can siblings register together?** A: Yes, and we offer a sibling discount. Contact us via WhatsApp or the contact page.",
      "Register your child today at mechetron.com/summer-camp. Batches fill fast — only 20 seats per batch in each city.",
    ],
  },
  {
    slug: "arduino-projects-beginners-india",
    title: "5 Easy Arduino Projects for Beginners in India — Build at Home",
    excerpt: "Five beginner-friendly Arduino projects you can build at home, with components list, step-by-step instructions and tips.",
    date: "2026-03-12",
    category: "Arduino",
    image: "/images/arduino-kit.webp",
    body: [
      "Arduino is the best entry point into the world of electronics and robotics — and for good reason. It's affordable (UNO costs ₹300–500 in India), beginner-friendly, and the global community means you'll never run out of project ideas or troubleshooting help. Here are five projects you can build this week.",
      "**Project 1 — LED Blink (Hello World of Hardware)**\nComponents: Arduino UNO, LED, 220Ω resistor, breadboard, USB cable. Time: 15 minutes. Connect the LED anode (+) to pin 13 through a 220Ω resistor, cathode to GND. Open Arduino IDE → Examples → Basics → Blink. Upload. The LED blinks every second. Now change the delay values and watch it respond. This is your first hardware interaction.",
      "**Project 2 — Temperature Monitor with LCD Display**\nComponents: Arduino, DHT11 sensor, 16×2 LCD display, 10kΩ potentiometer, jumper wires. Time: 45 minutes. The DHT11 reads temperature and humidity; the LCD displays them. This is your first sensor project. Tip: use the LiquidCrystal library from Arduino IDE's Library Manager. In India, both components cost under ₹150 total on Robu.in or Amazon.",
      "**Project 3 — Ultrasonic Distance Sensor**\nComponents: Arduino, HC-SR04 ultrasonic sensor, buzzer (optional), breadboard. Time: 30 minutes. The HC-SR04 sends a sound pulse and measures how long it takes to bounce back. Arduino converts this to centimeters. Add a buzzer that beeps faster as an object gets closer — you've just built a parking sensor. HC-SR04 costs ₹30–50 in India.",
      "**Project 4 — Servo Motor Control with Potentiometer**\nComponents: Arduino, SG90 servo motor, 10kΩ potentiometer. Time: 20 minutes. Wire the pot center pin to A0. In code, read the analog value (0–1023), map it to 0–180 degrees, and write to the servo. Turn the pot, watch the servo sweep. This is the foundation of robotic arms and RC vehicles. SG90 servos cost ₹60–80 in India.",
      "**Project 5 — Buzzer Alarm with Button**\nComponents: Arduino, active buzzer, push button, 10kΩ resistor. Time: 20 minutes. Wire the button to pin 2 with a pull-down resistor. Wire the buzzer to pin 8. When button is pressed, buzzer sounds. Add an LED that lights with the buzzer. This teaches digital input/output, pull-down resistors, and debouncing — three fundamental concepts.",
      "**Where to Buy Components in India**\nRobu.in and Thinkrobotics.in are the best online stores for Arduino components in India — fast delivery, genuine parts, and good prices. For local purchase in Hyderabad, visit SP Road. In Chennai, try Ritchie Street, George Town.",
      "**Why the Mech-E-Tron Arduino Kit Contains Everything**\nOur Arduino UNO Learning Board kit includes all components for 30+ projects — sensors, motors, displays, and a full project guidebook. It's designed so you never have to search for individual components. Available at mechetron.com/products/arduino-uno-learning-board.",
      "**FAQ**",
      "**Q: Which Arduino IDE version should I use?** A: Download Arduino IDE 2.x from arduino.cc. It has better code completion and serial plotter than older versions.",
      "**Q: My code uploads but nothing happens. What's wrong?** A: Check three things: 1) correct board selected in Tools → Board, 2) correct COM port selected, 3) LED is connected to the pin your code references.",
      "**Q: Can I use a Chinese clone Arduino?** A: Yes, but you may need to install CH340 drivers. Search 'CH340 driver Windows/Mac' and install before connecting.",
      "Ready to go further? Our **Arduino UNO Course at Mech-E-Tron** (₹2,999, 15 days) takes you from these basics to building real sensor systems and mini robots with a certificate at the end.",
    ],
  },
  {
    slug: "drone-training-india-dgca",
    title: "Drone Training Course in India — DGCA Certificate | Mech-E-Tron",
    excerpt: "Everything you need to know about drone training in India, DGCA certification, career opportunities, and why Mech-E-Tron's course stands apart.",
    date: "2026-03-05",
    category: "Robotics",
    image: "/images/drone-workshop.webp",
    body: [
      "India's drone industry is projected to be worth ₹15,000 crore by 2026, and the demand for trained drone operators, technicians, and engineers is growing faster than the supply. Whether you want a career in aerial photography, agriculture, defence, or real estate, **drone training in India** is one of the most future-proof skills you can acquire.",
      "**Types of Drones and What They're Used For**\nMultirotor drones (quadcopters, hexacopters): most common, used for photography and short-range delivery. Fixed-wing drones: longer range, used for mapping and agriculture. Hybrid VTOL: combines both. At Mech-E-Tron, we focus on multirotors in our workshop, with advanced fixed-wing content for specialisation.",
      "**How DGCA Certification Works in India**\nThe Directorate General of Civil Aviation (DGCA) is India's aviation regulatory body. Under the Drone Rules 2021, all operators of medium and large drones need a Remote Pilot Licence (RPL). Our Drone Workshop teaches DGCA guidelines and safety protocols. For students pursuing full RPL, we guide you through the DGCA Digital Sky Portal exam process and practical training requirements.",
      "**Career Paths in the Drone Industry**\nAerial Photography & Videography: ₹25,000–80,000/month for skilled operators. Agriculture Drone Services: Agri-drone spraying is a booming market with government subsidies. Real Estate Surveying: every major real estate project now uses aerial surveys. Defence & Security: UAV operators with technical training are sought by security agencies. Film Industry: Bollywood and OTT productions regularly hire drone pilots. Infrastructure Inspection: power lines, pipelines, and bridges are increasingly inspected by drone.",
      "**What Makes Mech-E-Tron's Drone Training Unique**\nOur drone workshop is delivered by a **retired Indian Air Force officer** with operational drone experience — a standard no other civilian training centre in Chennai or Hyderabad can match. Students don't just learn to fly; they build the drone from the frame up, understanding every component: motor selection, ESC configuration, flight controller PID tuning, GPS integration, and DGCA safety protocols.",
      "**What Students Build in the Workshop**\nDay 1: Frame assembly, motor mounting, propeller selection and balancing. Day 2: ESC wiring, flight controller configuration, first hover and flight. Students leave with a fully built and tested quadcopter and the technical knowledge to maintain and modify it.",
      "**Workshop Details**\nDuration: 2-day intensive. Fee: ₹2,500. Available in Chennai and Hyderabad. Certificate of completion included. Maximum 12 students per batch for adequate flight time per student.",
      "**FAQ — Drone Training India**",
      "**Q: Do I need any prior experience to join the drone workshop?** A: No. We start from the basics of aerodynamics and build up. If you've completed our Arduino course, you'll have a head start on the electronics.",
      "**Q: Will I be able to fly commercially after this workshop?** A: Our workshop teaches the technical foundation and DGCA awareness. For commercial operations, you'll need to register on DGCA's Digital Sky portal and obtain an RPL for medium/large drones. We guide you through this process.",
      "**Q: Are drones provided during the workshop?** A: Yes — we provide all components and tools. You build and fly during the session. You may optionally purchase the kit to take home.",
      "**Q: What is the scope of drone jobs in India in 2026?** A: The Ministry of Civil Aviation projects 10,000+ drone-related jobs by 2026. Agriculture, delivery, and infrastructure sectors are the highest-growth areas.",
      "**Q: Is DGCA certification mandatory for all drone pilots?** A: Only for medium (up to 25kg) and large drones. Nano drones (up to 250g) and micro drones (up to 2kg) in green zones have simplified rules. Our workshop covers all categories.",
      "Enrol in our **Drone Workshop** at mechetron.com/courses/drone-workshop or WhatsApp +91 8148435246 to check next batch availability.",
    ],
  },
  {
    slug: "stem-education-benefits-india",
    title: "Benefits of STEM Education for School Students in India — A Parent Guide",
    excerpt: "A comprehensive guide for parents on why STEM education matters, what real outcomes look like, and how to choose the right STEM program.",
    date: "2026-02-28",
    category: "STEM Education",
    image: "/images/classroom.webp",
    body: [
      "Every parent wants the best future for their child. In 2026, that future increasingly belongs to young people who understand how technology works — not just how to use it. **STEM education for school students in India** is the fastest and most affordable path to that future.",
      "**What STEM Education Actually Is**\nSTEM is Science, Technology, Engineering and Mathematics — but good STEM education is more than subjects. It's a way of thinking: observe a problem, hypothesise a solution, build it, test it, fail, improve, repeat. This design-thinking cycle is how every successful engineer, entrepreneur and scientist operates. Learning it at age 10 changes a child's relationship with every challenge they'll ever face.",
      "**Career Opportunities in Robotics and AI**\nIndia's technology sector is projected to employ 85 lakh people by 2030. The fastest-growing segments are: robotics and automation engineers (47% projected growth), AI/ML specialists (35% growth), IoT developers (30% growth), and drone operators and technicians (booming sector). Children who start robotics at age 10–14 will have 6–10 years of practical experience by the time they graduate — an enormous competitive advantage.",
      "**Why Practical Learning Beats Textbook Teaching**\nResearch consistently shows that students retain 70–80% of what they do, versus 10–20% of what they read. When a child builds a temperature sensor that triggers a fan, they understand electricity, control systems, and programming in a way that no textbook diagram can replicate. The hands-on experience also builds metacognitive skills — the ability to learn independently — that benefit every academic subject.",
      "**How Robotics Builds Life Skills**\nProblem solving: debugging a robot that doesn't work teaches systematic thinking. Persistence: every build has setbacks; learning to push through is invaluable. Teamwork: most robotics projects are collaborative. Communication: presenting a working robot to an audience builds confidence and articulation. Creativity: the best robots in our lab are always the ones where students went beyond the instructions.",
      "**What to Look for in a STEM Program**\nHands-on ratio: at least 70% of session time should be building and testing. Batch size: maximum 1:8 mentor ratio. Certification: AICRA is the gold standard for school robotics certificates in India. Physical components: avoid programs that use simulation software only. Track record: look for student competition wins and testimonials from parents.",
      "**How Mech-E-Tron Delivers Real STEM Outcomes**\nOur student outcomes speak for themselves: students have won podium finishes at WRC national competitions, B.Tech students have received distinction grades with our project support, and parents consistently report improved performance in Physics and Mathematics after our courses. We are AICRA District Coordinators, MSME registered, and ISO certified — credentials that reflect our commitment to quality.",
      "**FAQ for Parents**",
      "**Q: At what age should my child start STEM education?** A: Our Summer Camp accepts students from Grade 3 (age ~8). This is an excellent starting age. The Arduino course is recommended from Grade 6.",
      "**Q: How is this different from school Computer Science classes?** A: School CS teaches typing, Scratch, or theory. We teach electronics, sensor integration, motor control and real Arduino programming — skills that directly translate to engineering careers.",
      "**Q: Will this distract from board exam preparation?** A: Our students' board results are consistently strong. Practical STEM learning reinforces Physics, Math and CS concepts, making exams easier. Sessions are scheduled to not conflict with school hours.",
      "**Q: How much does quality STEM education cost?** A: Our Summer Camp is ₹2,299 (15 days). Arduino course ₹2,999 (15 days). Robotics course ₹3,999 (1 month). These are industry-leading prices for certified, hands-on training.",
      "Visit mechetron.com to explore courses in Chennai, Hyderabad and Tirupati. Book a free demo — no commitment required.",
    ],
  },
];

/* ── Site alias (backward compat for pages using `site`) ── */
export const site = {
  about:
    "Mech-E-Tron is India's hands-on robotics & STEM education platform — training the next generation of engineers through real robots, real code, and real projects. Founded in Hyderabad, we serve 10,000+ students and 120+ schools.",
  contact: {
    email: companyInfo.email,
    phone1: companyInfo.phone,
    phone2: companyInfo.phone2,
    whatsapp: `https://wa.me/${companyInfo.whatsapp}?text=Hi%2C%20I%27m%20interested%20in%20Mech-E-Tron%20courses`,
    address: `${companyInfo.address.line1}, ${companyInfo.address.line2}, ${companyInfo.address.line3} — ${companyInfo.address.pincode}`,
  },
};

/* ── Arduino UNO Learning Board Product ─────────────────── */
export const arduinoProduct = {
  name: "Arduino UNO Learning Board",
  tagline: "One kit. 30+ projects. Infinite possibilities.",
  price: "₹1,799",
  mrp: "₹2,499",
  sku: "MET-ARD-UNO-01",
  image: "/images/arduino-kit.webp",
  images: [
    "/images/arduino-kit.webp",
    "/images/arduino-components.webp",
    "/images/pcb-prototype.webp",
  ],
  badge: "Best Seller",
  inStock: true,
  deliveryDays: "3–5 business days",
  whatsappOrder: "918148435246",
  description:
    "The Mech-E-Tron Arduino UNO Learning Board is a complete starter kit designed for students, hobbyists, and engineers who want to master embedded systems hands-on. Everything you need to complete 30+ real projects — straight out of the box.",
  features: [
    "Arduino UNO R3 — original ATmega328P microcontroller",
    "Breadboard (830 tie-point) for circuit prototyping",
    "Ultrasonic sensor (HC-SR04) for distance measurement",
    "IR sensor module for line following & object detection",
    "DHT11 temperature & humidity sensor",
    "LDR (Light Dependent Resistor) + 10kΩ resistors",
    "Servo motor (SG90) for motion control",
    "L298N motor driver module for DC motor control",
    "2× DC motors with wheels for robot builds",
    "16×2 LCD display with I2C module",
    "HC-05 Bluetooth module for wireless control",
    "Assorted LEDs, push buttons, resistors & jumper wires",
    "USB-A to USB-B cable for programming",
    "Project guide PDF — 30+ step-by-step projects",
  ],
  projects: [
    "Line Following Robot",
    "Obstacle Avoidance Robot",
    "Bluetooth-Controlled Car",
    "Smart Home Automation",
    "Temperature & Humidity Monitor",
    "Automatic Street Light",
    "Distance Measuring Device",
    "Servo Motor Controller",
    "LCD Display Projects",
    "LED Chaser & Patterns",
    "Push Button Counter",
    "Buzzer Alarm System",
    "PWM Speed Controller",
    "Digital Voltmeter",
    "Traffic Light Simulation",
    "Gesture-Controlled Robot",
    "IR Remote Control",
    "Soil Moisture Sensor",
    "Fire Detection Alarm",
    "Gas Leakage Detector",
    "Digital Thermometer",
    "Sound Detection System",
    "Clap Switch Circuit",
    "Rain Detector",
    "Pulse Rate Monitor (simulated)",
    "4-Digit 7-Segment Display",
    "RFID Reader Integration",
    "IoT Weather Station (with WiFi module)",
    "Joystick-Controlled Robot",
    "Stepper Motor Driver",
    "Real-Time Clock (RTC)",
    "Data Logger to SD Card",
  ],
  whyChoose: [
    { icon: "📦", title: "Everything Included", body: "No hunting for extra components — every part needed for all 30+ projects is in the box." },
    { icon: "📖", title: "Step-by-Step Guides", body: "Detailed PDF project guide with circuit diagrams, code, and explanations for every project." },
    { icon: "🔧", title: "Mentor Support", body: "Stuck? WhatsApp our team for free technical support for 3 months after purchase." },
    { icon: "🚀", title: "Scalable Learning", body: "Start with blinking LEDs — build up to an autonomous robot. The kit grows with you." },
    { icon: "🏆", title: "Used in Our Courses", body: "The same kit used in all Mech-E-Tron offline and online programs. Continuity guaranteed." },
  ],
};

/* ── Technologies Taught ────────────────────────────────── */
export const technologies = [
  { name: "Arduino IDE", icon: "⚡", color: "#00979D", desc: "Microcontroller programming" },
  { name: "Python", icon: "🐍", color: "#3776AB", desc: "NumPy · Pandas · OpenCV" },
  { name: "C / C++", icon: "💾", color: "#00599C", desc: "Embedded firmware & algorithms" },
  { name: "Embedded C", icon: "🔧", color: "#FF6A00", desc: "Low-level MCU programming" },
  { name: "Raspberry Pi", icon: "🍓", color: "#C51A4A", desc: "Linux-based projects & vision" },
  { name: "IoT & ESP32", icon: "🌐", color: "#0E7FD0", desc: "Connected hardware & MQTT" },
  { name: "MATLAB / Simulink", icon: "📊", color: "#E16737", desc: "Control systems & AI models" },
  { name: "FPGA / ARM Cortex", icon: "🖥️", color: "#7B2FBE", desc: "Advanced embedded architecture" },
  { name: "PCB Design", icon: "🔌", color: "#2ECC71", desc: "KiCad & EasyEDA schematic design" },
  { name: "3D Printing", icon: "🖨️", color: "#E74C3C", desc: "FDM prototyping & part design" },
  { name: "Drones / DGCA", icon: "🛸", color: "#0B3D91", desc: "UAV build, fly & compliance" },
];

/* ── Why Choose Mech-E-Tron ─────────────────────────────── */
export const whyChoose = [
  {
    icon: "🔩",
    title: "Practical, Hands-On Learning",
    body: "Every concept is taught on real hardware. No simulations — you build, break, and fix actual robots and circuits.",
    accent: "#FF6A00",
  },
  {
    icon: "👨‍🏫",
    title: "Expert Mentors",
    body: "Learn from industry engineers and educators with real-world experience in embedded systems, robotics, and drones.",
    accent: "#0B3D91",
  },
  {
    icon: "📦",
    title: "Arduino UNO Kit Included",
    body: "Every student gets our custom Arduino UNO Learning Board with 30+ project guides — yours to keep after the course.",
    accent: "#00979D",
  },
  {
    icon: "🏆",
    title: "Competition Training",
    body: "We train students for WRO, RoboLeague, AICRA, and Smart India Hackathon — with dedicated coaching and mock rounds.",
    accent: "#FFB400",
  },
  {
    icon: "🎓",
    title: "Recognized Certification",
    body: "Earn an industry-recognized certificate from OTBI-incubated Mech-E-Tron, trusted by 120+ schools across India.",
    accent: "#2ECC71",
  },
];

/* ── Gallery Items ──────────────────────────────────────── */
export const galleryItems = [
  {
    title: "Line Following Robot",
    student: "Rahul S.",
    category: "Robotic",
    image: "/images/robotics-lab.webp",
  },
  {
    title: "Obstacle Avoidance Bot",
    student: "Priya R.",
    category: "Robotic",
    image: "/images/arduino-components.webp",
  },
  {
    title: "Custom Photography Drone",
    student: "Arjun K.",
    category: "Drones",
    image: "/images/drone-flying.webp",
  },
  {
    title: "Smart Home IoT System",
    student: "Sneha P.",
    category: "IoT",
    image: "/images/iot-project.webp",
  },
  {
    title: "3D Printed Robot Chassis",
    student: "Vikram M.",
    category: "3D Printing",
    image: "/images/3d-printing.webp",
  },
  {
    title: "Arduino Weather Station",
    student: "Meera D.",
    category: "Arduino",
    image: "/images/arduino-kit.webp",
  },
  {
    title: "Bluetooth Car Controller",
    student: "Karthik N.",
    category: "Arduino",
    image: "/images/rc-car.webp",
  },
  {
    title: "Maze Solving Robot",
    student: "Ananya G.",
    category: "Robotic",
    image: "/images/stem-school.webp",
  },
];
